// Code generated by cmd/vipsx-gen from libvips 8.18.4. DO NOT EDIT.
//
// Regenerate with:
//
//	go run ./cmd/vipsx-gen -out vips
//
// Every function here is a thin wrapper over Call. Nothing in this file knows
// anything the installed libvips did not report, and none of it is C.

package vips

// Access mirrors the libvips VipsAccess type.
type Access int

const (
	// AccessRandom is "random".
	AccessRandom Access = 0
	// AccessSequential is "sequential".
	AccessSequential Access = 1
	// AccessSequentialUnbuffered is "sequential-unbuffered".
	AccessSequentialUnbuffered Access = 2
)

// String returns the libvips nickname for this value.
func (v Access) String() string {
	switch v {
	case 0:
		return "random"
	case 1:
		return "sequential"
	case 2:
		return "sequential-unbuffered"
	}
	return "Access(" + itoa(int(v)) + ")"
}

// Align mirrors the libvips VipsAlign type.
type Align int

const (
	// AlignLow is "low".
	AlignLow Align = 0
	// AlignCentre is "centre".
	AlignCentre Align = 1
	// AlignHigh is "high".
	AlignHigh Align = 2
)

// String returns the libvips nickname for this value.
func (v Align) String() string {
	switch v {
	case 0:
		return "low"
	case 1:
		return "centre"
	case 2:
		return "high"
	}
	return "Align(" + itoa(int(v)) + ")"
}

// Angle mirrors the libvips VipsAngle type.
type Angle int

const (
	// AngleD0 is "d0".
	AngleD0 Angle = 0
	// AngleD90 is "d90".
	AngleD90 Angle = 1
	// AngleD180 is "d180".
	AngleD180 Angle = 2
	// AngleD270 is "d270".
	AngleD270 Angle = 3
)

// String returns the libvips nickname for this value.
func (v Angle) String() string {
	switch v {
	case 0:
		return "d0"
	case 1:
		return "d90"
	case 2:
		return "d180"
	case 3:
		return "d270"
	}
	return "Angle(" + itoa(int(v)) + ")"
}

// Angle45 mirrors the libvips VipsAngle45 type.
type Angle45 int

const (
	// Angle45D0 is "d0".
	Angle45D0 Angle45 = 0
	// Angle45D45 is "d45".
	Angle45D45 Angle45 = 1
	// Angle45D90 is "d90".
	Angle45D90 Angle45 = 2
	// Angle45D135 is "d135".
	Angle45D135 Angle45 = 3
	// Angle45D180 is "d180".
	Angle45D180 Angle45 = 4
	// Angle45D225 is "d225".
	Angle45D225 Angle45 = 5
	// Angle45D270 is "d270".
	Angle45D270 Angle45 = 6
	// Angle45D315 is "d315".
	Angle45D315 Angle45 = 7
)

// String returns the libvips nickname for this value.
func (v Angle45) String() string {
	switch v {
	case 0:
		return "d0"
	case 1:
		return "d45"
	case 2:
		return "d90"
	case 3:
		return "d135"
	case 4:
		return "d180"
	case 5:
		return "d225"
	case 6:
		return "d270"
	case 7:
		return "d315"
	}
	return "Angle45(" + itoa(int(v)) + ")"
}

// BandFormat mirrors the libvips VipsBandFormat type.
type BandFormat int

const (
	// BandFormatNotset is "notset".
	BandFormatNotset BandFormat = -1
	// BandFormatUchar is "uchar".
	BandFormatUchar BandFormat = 0
	// BandFormatChar is "char".
	BandFormatChar BandFormat = 1
	// BandFormatUshort is "ushort".
	BandFormatUshort BandFormat = 2
	// BandFormatShort is "short".
	BandFormatShort BandFormat = 3
	// BandFormatUint is "uint".
	BandFormatUint BandFormat = 4
	// BandFormatInt is "int".
	BandFormatInt BandFormat = 5
	// BandFormatFloat is "float".
	BandFormatFloat BandFormat = 6
	// BandFormatComplex is "complex".
	BandFormatComplex BandFormat = 7
	// BandFormatDouble is "double".
	BandFormatDouble BandFormat = 8
	// BandFormatDpcomplex is "dpcomplex".
	BandFormatDpcomplex BandFormat = 9
)

// String returns the libvips nickname for this value.
func (v BandFormat) String() string {
	switch v {
	case -1:
		return "notset"
	case 0:
		return "uchar"
	case 1:
		return "char"
	case 2:
		return "ushort"
	case 3:
		return "short"
	case 4:
		return "uint"
	case 5:
		return "int"
	case 6:
		return "float"
	case 7:
		return "complex"
	case 8:
		return "double"
	case 9:
		return "dpcomplex"
	}
	return "BandFormat(" + itoa(int(v)) + ")"
}

// BlendMode mirrors the libvips VipsBlendMode type.
type BlendMode int

const (
	// BlendModeClear is "clear".
	BlendModeClear BlendMode = 0
	// BlendModeSource is "source".
	BlendModeSource BlendMode = 1
	// BlendModeOver is "over".
	BlendModeOver BlendMode = 2
	// BlendModeIn is "in".
	BlendModeIn BlendMode = 3
	// BlendModeOut is "out".
	BlendModeOut BlendMode = 4
	// BlendModeAtop is "atop".
	BlendModeAtop BlendMode = 5
	// BlendModeDest is "dest".
	BlendModeDest BlendMode = 6
	// BlendModeDestOver is "dest-over".
	BlendModeDestOver BlendMode = 7
	// BlendModeDestIn is "dest-in".
	BlendModeDestIn BlendMode = 8
	// BlendModeDestOut is "dest-out".
	BlendModeDestOut BlendMode = 9
	// BlendModeDestAtop is "dest-atop".
	BlendModeDestAtop BlendMode = 10
	// BlendModeXor is "xor".
	BlendModeXor BlendMode = 11
	// BlendModeAdd is "add".
	BlendModeAdd BlendMode = 12
	// BlendModeSaturate is "saturate".
	BlendModeSaturate BlendMode = 13
	// BlendModeMultiply is "multiply".
	BlendModeMultiply BlendMode = 14
	// BlendModeScreen is "screen".
	BlendModeScreen BlendMode = 15
	// BlendModeOverlay is "overlay".
	BlendModeOverlay BlendMode = 16
	// BlendModeDarken is "darken".
	BlendModeDarken BlendMode = 17
	// BlendModeLighten is "lighten".
	BlendModeLighten BlendMode = 18
	// BlendModeColourDodge is "colour-dodge".
	BlendModeColourDodge BlendMode = 19
	// BlendModeColourBurn is "colour-burn".
	BlendModeColourBurn BlendMode = 20
	// BlendModeHardLight is "hard-light".
	BlendModeHardLight BlendMode = 21
	// BlendModeSoftLight is "soft-light".
	BlendModeSoftLight BlendMode = 22
	// BlendModeDifference is "difference".
	BlendModeDifference BlendMode = 23
	// BlendModeExclusion is "exclusion".
	BlendModeExclusion BlendMode = 24
)

// String returns the libvips nickname for this value.
func (v BlendMode) String() string {
	switch v {
	case 0:
		return "clear"
	case 1:
		return "source"
	case 2:
		return "over"
	case 3:
		return "in"
	case 4:
		return "out"
	case 5:
		return "atop"
	case 6:
		return "dest"
	case 7:
		return "dest-over"
	case 8:
		return "dest-in"
	case 9:
		return "dest-out"
	case 10:
		return "dest-atop"
	case 11:
		return "xor"
	case 12:
		return "add"
	case 13:
		return "saturate"
	case 14:
		return "multiply"
	case 15:
		return "screen"
	case 16:
		return "overlay"
	case 17:
		return "darken"
	case 18:
		return "lighten"
	case 19:
		return "colour-dodge"
	case 20:
		return "colour-burn"
	case 21:
		return "hard-light"
	case 22:
		return "soft-light"
	case 23:
		return "difference"
	case 24:
		return "exclusion"
	}
	return "BlendMode(" + itoa(int(v)) + ")"
}

// Coding mirrors the libvips VipsCoding type.
type Coding int

const (
	// CodingError is "error".
	CodingError Coding = -1
	// CodingNone is "none".
	CodingNone Coding = 0
	// CodingLabq is "labq".
	CodingLabq Coding = 2
	// CodingRad is "rad".
	CodingRad Coding = 6
)

// String returns the libvips nickname for this value.
func (v Coding) String() string {
	switch v {
	case -1:
		return "error"
	case 0:
		return "none"
	case 2:
		return "labq"
	case 6:
		return "rad"
	}
	return "Coding(" + itoa(int(v)) + ")"
}

// Combine mirrors the libvips VipsCombine type.
type Combine int

const (
	// CombineMax is "max".
	CombineMax Combine = 0
	// CombineSum is "sum".
	CombineSum Combine = 1
	// CombineMin is "min".
	CombineMin Combine = 2
)

// String returns the libvips nickname for this value.
func (v Combine) String() string {
	switch v {
	case 0:
		return "max"
	case 1:
		return "sum"
	case 2:
		return "min"
	}
	return "Combine(" + itoa(int(v)) + ")"
}

// CombineMode mirrors the libvips VipsCombineMode type.
type CombineMode int

const (
	// CombineModeSet is "set".
	CombineModeSet CombineMode = 0
	// CombineModeAdd is "add".
	CombineModeAdd CombineMode = 1
)

// String returns the libvips nickname for this value.
func (v CombineMode) String() string {
	switch v {
	case 0:
		return "set"
	case 1:
		return "add"
	}
	return "CombineMode(" + itoa(int(v)) + ")"
}

// CompassDirection mirrors the libvips VipsCompassDirection type.
type CompassDirection int

const (
	// CompassDirectionCentre is "centre".
	CompassDirectionCentre CompassDirection = 0
	// CompassDirectionNorth is "north".
	CompassDirectionNorth CompassDirection = 1
	// CompassDirectionEast is "east".
	CompassDirectionEast CompassDirection = 2
	// CompassDirectionSouth is "south".
	CompassDirectionSouth CompassDirection = 3
	// CompassDirectionWest is "west".
	CompassDirectionWest CompassDirection = 4
	// CompassDirectionNorthEast is "north-east".
	CompassDirectionNorthEast CompassDirection = 5
	// CompassDirectionSouthEast is "south-east".
	CompassDirectionSouthEast CompassDirection = 6
	// CompassDirectionSouthWest is "south-west".
	CompassDirectionSouthWest CompassDirection = 7
	// CompassDirectionNorthWest is "north-west".
	CompassDirectionNorthWest CompassDirection = 8
)

// String returns the libvips nickname for this value.
func (v CompassDirection) String() string {
	switch v {
	case 0:
		return "centre"
	case 1:
		return "north"
	case 2:
		return "east"
	case 3:
		return "south"
	case 4:
		return "west"
	case 5:
		return "north-east"
	case 6:
		return "south-east"
	case 7:
		return "south-west"
	case 8:
		return "north-west"
	}
	return "CompassDirection(" + itoa(int(v)) + ")"
}

// Direction mirrors the libvips VipsDirection type.
type Direction int

const (
	// DirectionHorizontal is "horizontal".
	DirectionHorizontal Direction = 0
	// DirectionVertical is "vertical".
	DirectionVertical Direction = 1
)

// String returns the libvips nickname for this value.
func (v Direction) String() string {
	switch v {
	case 0:
		return "horizontal"
	case 1:
		return "vertical"
	}
	return "Direction(" + itoa(int(v)) + ")"
}

// Extend mirrors the libvips VipsExtend type.
type Extend int

const (
	// ExtendBlack is "black".
	ExtendBlack Extend = 0
	// ExtendCopy is "copy".
	ExtendCopy Extend = 1
	// ExtendRepeat is "repeat".
	ExtendRepeat Extend = 2
	// ExtendMirror is "mirror".
	ExtendMirror Extend = 3
	// ExtendWhite is "white".
	ExtendWhite Extend = 4
	// ExtendBackground is "background".
	ExtendBackground Extend = 5
)

// String returns the libvips nickname for this value.
func (v Extend) String() string {
	switch v {
	case 0:
		return "black"
	case 1:
		return "copy"
	case 2:
		return "repeat"
	case 3:
		return "mirror"
	case 4:
		return "white"
	case 5:
		return "background"
	}
	return "Extend(" + itoa(int(v)) + ")"
}

// FailOn mirrors the libvips VipsFailOn type.
type FailOn int

const (
	// FailOnNone is "none".
	FailOnNone FailOn = 0
	// FailOnTruncated is "truncated".
	FailOnTruncated FailOn = 1
	// FailOnError is "error".
	FailOnError FailOn = 2
	// FailOnWarning is "warning".
	FailOnWarning FailOn = 3
)

// String returns the libvips nickname for this value.
func (v FailOn) String() string {
	switch v {
	case 0:
		return "none"
	case 1:
		return "truncated"
	case 2:
		return "error"
	case 3:
		return "warning"
	}
	return "FailOn(" + itoa(int(v)) + ")"
}

// DzContainer mirrors the libvips VipsForeignDzContainer type.
type DzContainer int

const (
	// DzContainerFs is "fs".
	DzContainerFs DzContainer = 0
	// DzContainerZip is "zip".
	DzContainerZip DzContainer = 1
	// DzContainerSzi is "szi".
	DzContainerSzi DzContainer = 2
)

// String returns the libvips nickname for this value.
func (v DzContainer) String() string {
	switch v {
	case 0:
		return "fs"
	case 1:
		return "zip"
	case 2:
		return "szi"
	}
	return "DzContainer(" + itoa(int(v)) + ")"
}

// DzDepth mirrors the libvips VipsForeignDzDepth type.
type DzDepth int

const (
	// DzDepthOnepixel is "onepixel".
	DzDepthOnepixel DzDepth = 0
	// DzDepthOnetile is "onetile".
	DzDepthOnetile DzDepth = 1
	// DzDepthOne is "one".
	DzDepthOne DzDepth = 2
)

// String returns the libvips nickname for this value.
func (v DzDepth) String() string {
	switch v {
	case 0:
		return "onepixel"
	case 1:
		return "onetile"
	case 2:
		return "one"
	}
	return "DzDepth(" + itoa(int(v)) + ")"
}

// DzLayout mirrors the libvips VipsForeignDzLayout type.
type DzLayout int

const (
	// DzLayoutDz is "dz".
	DzLayoutDz DzLayout = 0
	// DzLayoutZoomify is "zoomify".
	DzLayoutZoomify DzLayout = 1
	// DzLayoutGoogle is "google".
	DzLayoutGoogle DzLayout = 2
	// DzLayoutIiif is "iiif".
	DzLayoutIiif DzLayout = 3
	// DzLayoutIiif3 is "iiif3".
	DzLayoutIiif3 DzLayout = 4
)

// String returns the libvips nickname for this value.
func (v DzLayout) String() string {
	switch v {
	case 0:
		return "dz"
	case 1:
		return "zoomify"
	case 2:
		return "google"
	case 3:
		return "iiif"
	case 4:
		return "iiif3"
	}
	return "DzLayout(" + itoa(int(v)) + ")"
}

// Flags mirrors the libvips VipsForeignFlags type.
type Flags int

const (
	// FlagsNone is "none".
	FlagsNone Flags = 0
	// FlagsPartial is "partial".
	FlagsPartial Flags = 1
	// FlagsBigendian is "bigendian".
	FlagsBigendian Flags = 2
	// FlagsSequential is "sequential".
	FlagsSequential Flags = 4
	// FlagsAll is "all".
	FlagsAll Flags = 7
)

// String returns the libvips nickname for this value.
func (v Flags) String() string {
	switch v {
	case 0:
		return "none"
	case 1:
		return "partial"
	case 2:
		return "bigendian"
	case 4:
		return "sequential"
	case 7:
		return "all"
	}
	return "Flags(" + itoa(int(v)) + ")"
}

// HeifCompression mirrors the libvips VipsForeignHeifCompression type.
type HeifCompression int

const (
	// HeifCompressionHevc is "hevc".
	HeifCompressionHevc HeifCompression = 1
	// HeifCompressionAvc is "avc".
	HeifCompressionAvc HeifCompression = 2
	// HeifCompressionJpeg is "jpeg".
	HeifCompressionJpeg HeifCompression = 3
	// HeifCompressionAv1 is "av1".
	HeifCompressionAv1 HeifCompression = 4
)

// String returns the libvips nickname for this value.
func (v HeifCompression) String() string {
	switch v {
	case 1:
		return "hevc"
	case 2:
		return "avc"
	case 3:
		return "jpeg"
	case 4:
		return "av1"
	}
	return "HeifCompression(" + itoa(int(v)) + ")"
}

// HeifEncoder mirrors the libvips VipsForeignHeifEncoder type.
type HeifEncoder int

const (
	// HeifEncoderAuto is "auto".
	HeifEncoderAuto HeifEncoder = 0
	// HeifEncoderAom is "aom".
	HeifEncoderAom HeifEncoder = 1
	// HeifEncoderRav1e is "rav1e".
	HeifEncoderRav1e HeifEncoder = 2
	// HeifEncoderSvt is "svt".
	HeifEncoderSvt HeifEncoder = 3
	// HeifEncoderX265 is "x265".
	HeifEncoderX265 HeifEncoder = 4
)

// String returns the libvips nickname for this value.
func (v HeifEncoder) String() string {
	switch v {
	case 0:
		return "auto"
	case 1:
		return "aom"
	case 2:
		return "rav1e"
	case 3:
		return "svt"
	case 4:
		return "x265"
	}
	return "HeifEncoder(" + itoa(int(v)) + ")"
}

// Keep mirrors the libvips VipsForeignKeep type.
type Keep int

const (
	// KeepNone is "none".
	KeepNone Keep = 0
	// KeepExif is "exif".
	KeepExif Keep = 1
	// KeepXmp is "xmp".
	KeepXmp Keep = 2
	// KeepIptc is "iptc".
	KeepIptc Keep = 4
	// KeepIcc is "icc".
	KeepIcc Keep = 8
	// KeepOther is "other".
	KeepOther Keep = 16
	// KeepGainmap is "gainmap".
	KeepGainmap Keep = 32
	// KeepAll is "all".
	KeepAll Keep = 63
)

// String returns the libvips nickname for this value.
func (v Keep) String() string {
	switch v {
	case 0:
		return "none"
	case 1:
		return "exif"
	case 2:
		return "xmp"
	case 4:
		return "iptc"
	case 8:
		return "icc"
	case 16:
		return "other"
	case 32:
		return "gainmap"
	case 63:
		return "all"
	}
	return "Keep(" + itoa(int(v)) + ")"
}

// PdfPageBox mirrors the libvips VipsForeignPdfPageBox type.
type PdfPageBox int

const (
	// PdfPageBoxMedia is "media".
	PdfPageBoxMedia PdfPageBox = 0
	// PdfPageBoxCrop is "crop".
	PdfPageBoxCrop PdfPageBox = 1
	// PdfPageBoxTrim is "trim".
	PdfPageBoxTrim PdfPageBox = 2
	// PdfPageBoxBleed is "bleed".
	PdfPageBoxBleed PdfPageBox = 3
	// PdfPageBoxArt is "art".
	PdfPageBoxArt PdfPageBox = 4
)

// String returns the libvips nickname for this value.
func (v PdfPageBox) String() string {
	switch v {
	case 0:
		return "media"
	case 1:
		return "crop"
	case 2:
		return "trim"
	case 3:
		return "bleed"
	case 4:
		return "art"
	}
	return "PdfPageBox(" + itoa(int(v)) + ")"
}

// PngFilter mirrors the libvips VipsForeignPngFilter type.
type PngFilter int

const (
	// PngFilterNone is "none".
	PngFilterNone PngFilter = 8
	// PngFilterSub is "sub".
	PngFilterSub PngFilter = 16
	// PngFilterUp is "up".
	PngFilterUp PngFilter = 32
	// PngFilterAvg is "avg".
	PngFilterAvg PngFilter = 64
	// PngFilterPaeth is "paeth".
	PngFilterPaeth PngFilter = 128
	// PngFilterAll is "all".
	PngFilterAll PngFilter = 248
)

// String returns the libvips nickname for this value.
func (v PngFilter) String() string {
	switch v {
	case 8:
		return "none"
	case 16:
		return "sub"
	case 32:
		return "up"
	case 64:
		return "avg"
	case 128:
		return "paeth"
	case 248:
		return "all"
	}
	return "PngFilter(" + itoa(int(v)) + ")"
}

// PpmFormat mirrors the libvips VipsForeignPpmFormat type.
type PpmFormat int

const (
	// PpmFormatPbm is "pbm".
	PpmFormatPbm PpmFormat = 0
	// PpmFormatPgm is "pgm".
	PpmFormatPgm PpmFormat = 1
	// PpmFormatPpm is "ppm".
	PpmFormatPpm PpmFormat = 2
	// PpmFormatPfm is "pfm".
	PpmFormatPfm PpmFormat = 3
	// PpmFormatPnm is "pnm".
	PpmFormatPnm PpmFormat = 4
)

// String returns the libvips nickname for this value.
func (v PpmFormat) String() string {
	switch v {
	case 0:
		return "pbm"
	case 1:
		return "pgm"
	case 2:
		return "ppm"
	case 3:
		return "pfm"
	case 4:
		return "pnm"
	}
	return "PpmFormat(" + itoa(int(v)) + ")"
}

// ForeignSubsample mirrors the libvips VipsForeignSubsample type.
type ForeignSubsample int

const (
	// ForeignSubsampleAuto is "auto".
	ForeignSubsampleAuto ForeignSubsample = 0
	// ForeignSubsampleOn is "on".
	ForeignSubsampleOn ForeignSubsample = 1
	// ForeignSubsampleOff is "off".
	ForeignSubsampleOff ForeignSubsample = 2
)

// String returns the libvips nickname for this value.
func (v ForeignSubsample) String() string {
	switch v {
	case 0:
		return "auto"
	case 1:
		return "on"
	case 2:
		return "off"
	}
	return "ForeignSubsample(" + itoa(int(v)) + ")"
}

// TiffCompression mirrors the libvips VipsForeignTiffCompression type.
type TiffCompression int

const (
	// TiffCompressionNone is "none".
	TiffCompressionNone TiffCompression = 0
	// TiffCompressionJpeg is "jpeg".
	TiffCompressionJpeg TiffCompression = 1
	// TiffCompressionDeflate is "deflate".
	TiffCompressionDeflate TiffCompression = 2
	// TiffCompressionPackbits is "packbits".
	TiffCompressionPackbits TiffCompression = 3
	// TiffCompressionCcittfax4 is "ccittfax4".
	TiffCompressionCcittfax4 TiffCompression = 4
	// TiffCompressionLzw is "lzw".
	TiffCompressionLzw TiffCompression = 5
	// TiffCompressionWebp is "webp".
	TiffCompressionWebp TiffCompression = 6
	// TiffCompressionZstd is "zstd".
	TiffCompressionZstd TiffCompression = 7
	// TiffCompressionJp2k is "jp2k".
	TiffCompressionJp2k TiffCompression = 8
)

// String returns the libvips nickname for this value.
func (v TiffCompression) String() string {
	switch v {
	case 0:
		return "none"
	case 1:
		return "jpeg"
	case 2:
		return "deflate"
	case 3:
		return "packbits"
	case 4:
		return "ccittfax4"
	case 5:
		return "lzw"
	case 6:
		return "webp"
	case 7:
		return "zstd"
	case 8:
		return "jp2k"
	}
	return "TiffCompression(" + itoa(int(v)) + ")"
}

// TiffPredictor mirrors the libvips VipsForeignTiffPredictor type.
type TiffPredictor int

const (
	// TiffPredictorNone is "none".
	TiffPredictorNone TiffPredictor = 1
	// TiffPredictorHorizontal is "horizontal".
	TiffPredictorHorizontal TiffPredictor = 2
	// TiffPredictorFloat is "float".
	TiffPredictorFloat TiffPredictor = 3
)

// String returns the libvips nickname for this value.
func (v TiffPredictor) String() string {
	switch v {
	case 1:
		return "none"
	case 2:
		return "horizontal"
	case 3:
		return "float"
	}
	return "TiffPredictor(" + itoa(int(v)) + ")"
}

// TiffResunit mirrors the libvips VipsForeignTiffResunit type.
type TiffResunit int

const (
	// TiffResunitCm is "cm".
	TiffResunitCm TiffResunit = 0
	// TiffResunitInch is "inch".
	TiffResunitInch TiffResunit = 1
)

// String returns the libvips nickname for this value.
func (v TiffResunit) String() string {
	switch v {
	case 0:
		return "cm"
	case 1:
		return "inch"
	}
	return "TiffResunit(" + itoa(int(v)) + ")"
}

// WebpPreset mirrors the libvips VipsForeignWebpPreset type.
type WebpPreset int

const (
	// WebpPresetDefault is "default".
	WebpPresetDefault WebpPreset = 0
	// WebpPresetPicture is "picture".
	WebpPresetPicture WebpPreset = 1
	// WebpPresetPhoto is "photo".
	WebpPresetPhoto WebpPreset = 2
	// WebpPresetDrawing is "drawing".
	WebpPresetDrawing WebpPreset = 3
	// WebpPresetIcon is "icon".
	WebpPresetIcon WebpPreset = 4
	// WebpPresetText is "text".
	WebpPresetText WebpPreset = 5
)

// String returns the libvips nickname for this value.
func (v WebpPreset) String() string {
	switch v {
	case 0:
		return "default"
	case 1:
		return "picture"
	case 2:
		return "photo"
	case 3:
		return "drawing"
	case 4:
		return "icon"
	case 5:
		return "text"
	}
	return "WebpPreset(" + itoa(int(v)) + ")"
}

// Intent mirrors the libvips VipsIntent type.
type Intent int

const (
	// IntentPerceptual is "perceptual".
	IntentPerceptual Intent = 0
	// IntentRelative is "relative".
	IntentRelative Intent = 1
	// IntentSaturation is "saturation".
	IntentSaturation Intent = 2
	// IntentAbsolute is "absolute".
	IntentAbsolute Intent = 3
	// IntentAuto is "auto".
	IntentAuto Intent = 32
)

// String returns the libvips nickname for this value.
func (v Intent) String() string {
	switch v {
	case 0:
		return "perceptual"
	case 1:
		return "relative"
	case 2:
		return "saturation"
	case 3:
		return "absolute"
	case 32:
		return "auto"
	}
	return "Intent(" + itoa(int(v)) + ")"
}

// Interesting mirrors the libvips VipsInteresting type.
type Interesting int

const (
	// InterestingNone is "none".
	InterestingNone Interesting = 0
	// InterestingCentre is "centre".
	InterestingCentre Interesting = 1
	// InterestingEntropy is "entropy".
	InterestingEntropy Interesting = 2
	// InterestingAttention is "attention".
	InterestingAttention Interesting = 3
	// InterestingLow is "low".
	InterestingLow Interesting = 4
	// InterestingHigh is "high".
	InterestingHigh Interesting = 5
	// InterestingAll is "all".
	InterestingAll Interesting = 6
)

// String returns the libvips nickname for this value.
func (v Interesting) String() string {
	switch v {
	case 0:
		return "none"
	case 1:
		return "centre"
	case 2:
		return "entropy"
	case 3:
		return "attention"
	case 4:
		return "low"
	case 5:
		return "high"
	case 6:
		return "all"
	}
	return "Interesting(" + itoa(int(v)) + ")"
}

// Interpretation mirrors the libvips VipsInterpretation type.
type Interpretation int

const (
	// InterpretationError is "error".
	InterpretationError Interpretation = -1
	// InterpretationMultiband is "multiband".
	InterpretationMultiband Interpretation = 0
	// InterpretationBW is "b-w".
	InterpretationBW Interpretation = 1
	// InterpretationHistogram is "histogram".
	InterpretationHistogram Interpretation = 10
	// InterpretationXyz is "xyz".
	InterpretationXyz Interpretation = 12
	// InterpretationLab is "lab".
	InterpretationLab Interpretation = 13
	// InterpretationCmyk is "cmyk".
	InterpretationCmyk Interpretation = 15
	// InterpretationLabq is "labq".
	InterpretationLabq Interpretation = 16
	// InterpretationRgb is "rgb".
	InterpretationRgb Interpretation = 17
	// InterpretationCmc is "cmc".
	InterpretationCmc Interpretation = 18
	// InterpretationLch is "lch".
	InterpretationLch Interpretation = 19
	// InterpretationLabs is "labs".
	InterpretationLabs Interpretation = 21
	// InterpretationSrgb is "srgb".
	InterpretationSrgb Interpretation = 22
	// InterpretationYxy is "yxy".
	InterpretationYxy Interpretation = 23
	// InterpretationFourier is "fourier".
	InterpretationFourier Interpretation = 24
	// InterpretationRgb16 is "rgb16".
	InterpretationRgb16 Interpretation = 25
	// InterpretationGrey16 is "grey16".
	InterpretationGrey16 Interpretation = 26
	// InterpretationMatrix is "matrix".
	InterpretationMatrix Interpretation = 27
	// InterpretationScrgb is "scrgb".
	InterpretationScrgb Interpretation = 28
	// InterpretationHsv is "hsv".
	InterpretationHsv Interpretation = 29
	// InterpretationOklab is "oklab".
	InterpretationOklab Interpretation = 30
	// InterpretationOklch is "oklch".
	InterpretationOklch Interpretation = 31
)

// String returns the libvips nickname for this value.
func (v Interpretation) String() string {
	switch v {
	case -1:
		return "error"
	case 0:
		return "multiband"
	case 1:
		return "b-w"
	case 10:
		return "histogram"
	case 12:
		return "xyz"
	case 13:
		return "lab"
	case 15:
		return "cmyk"
	case 16:
		return "labq"
	case 17:
		return "rgb"
	case 18:
		return "cmc"
	case 19:
		return "lch"
	case 21:
		return "labs"
	case 22:
		return "srgb"
	case 23:
		return "yxy"
	case 24:
		return "fourier"
	case 25:
		return "rgb16"
	case 26:
		return "grey16"
	case 27:
		return "matrix"
	case 28:
		return "scrgb"
	case 29:
		return "hsv"
	case 30:
		return "oklab"
	case 31:
		return "oklch"
	}
	return "Interpretation(" + itoa(int(v)) + ")"
}

// Kernel mirrors the libvips VipsKernel type.
type Kernel int

const (
	// KernelNearest is "nearest".
	KernelNearest Kernel = 0
	// KernelLinear is "linear".
	KernelLinear Kernel = 1
	// KernelCubic is "cubic".
	KernelCubic Kernel = 2
	// KernelMitchell is "mitchell".
	KernelMitchell Kernel = 3
	// KernelLanczos2 is "lanczos2".
	KernelLanczos2 Kernel = 4
	// KernelLanczos3 is "lanczos3".
	KernelLanczos3 Kernel = 5
	// KernelMks2013 is "mks2013".
	KernelMks2013 Kernel = 6
	// KernelMks2021 is "mks2021".
	KernelMks2021 Kernel = 7
)

// String returns the libvips nickname for this value.
func (v Kernel) String() string {
	switch v {
	case 0:
		return "nearest"
	case 1:
		return "linear"
	case 2:
		return "cubic"
	case 3:
		return "mitchell"
	case 4:
		return "lanczos2"
	case 5:
		return "lanczos3"
	case 6:
		return "mks2013"
	case 7:
		return "mks2021"
	}
	return "Kernel(" + itoa(int(v)) + ")"
}

// OperationBoolean mirrors the libvips VipsOperationBoolean type.
type OperationBoolean int

const (
	// OperationBooleanAnd is "and".
	OperationBooleanAnd OperationBoolean = 0
	// OperationBooleanOr is "or".
	OperationBooleanOr OperationBoolean = 1
	// OperationBooleanEor is "eor".
	OperationBooleanEor OperationBoolean = 2
	// OperationBooleanLshift is "lshift".
	OperationBooleanLshift OperationBoolean = 3
	// OperationBooleanRshift is "rshift".
	OperationBooleanRshift OperationBoolean = 4
)

// String returns the libvips nickname for this value.
func (v OperationBoolean) String() string {
	switch v {
	case 0:
		return "and"
	case 1:
		return "or"
	case 2:
		return "eor"
	case 3:
		return "lshift"
	case 4:
		return "rshift"
	}
	return "OperationBoolean(" + itoa(int(v)) + ")"
}

// OperationComplex mirrors the libvips VipsOperationComplex type.
type OperationComplex int

const (
	// OperationComplexPolar is "polar".
	OperationComplexPolar OperationComplex = 0
	// OperationComplexRect is "rect".
	OperationComplexRect OperationComplex = 1
	// OperationComplexConj is "conj".
	OperationComplexConj OperationComplex = 2
)

// String returns the libvips nickname for this value.
func (v OperationComplex) String() string {
	switch v {
	case 0:
		return "polar"
	case 1:
		return "rect"
	case 2:
		return "conj"
	}
	return "OperationComplex(" + itoa(int(v)) + ")"
}

// OperationComplex2 mirrors the libvips VipsOperationComplex2 type.
type OperationComplex2 int

const (
	// OperationComplex2CrossPhase is "cross-phase".
	OperationComplex2CrossPhase OperationComplex2 = 0
)

// String returns the libvips nickname for this value.
func (v OperationComplex2) String() string {
	switch v {
	case 0:
		return "cross-phase"
	}
	return "OperationComplex2(" + itoa(int(v)) + ")"
}

// OperationComplexget mirrors the libvips VipsOperationComplexget type.
type OperationComplexget int

const (
	// OperationComplexgetReal is "real".
	OperationComplexgetReal OperationComplexget = 0
	// OperationComplexgetImag is "imag".
	OperationComplexgetImag OperationComplexget = 1
)

// String returns the libvips nickname for this value.
func (v OperationComplexget) String() string {
	switch v {
	case 0:
		return "real"
	case 1:
		return "imag"
	}
	return "OperationComplexget(" + itoa(int(v)) + ")"
}

// OperationMath mirrors the libvips VipsOperationMath type.
type OperationMath int

const (
	// OperationMathSin is "sin".
	OperationMathSin OperationMath = 0
	// OperationMathCos is "cos".
	OperationMathCos OperationMath = 1
	// OperationMathTan is "tan".
	OperationMathTan OperationMath = 2
	// OperationMathAsin is "asin".
	OperationMathAsin OperationMath = 3
	// OperationMathAcos is "acos".
	OperationMathAcos OperationMath = 4
	// OperationMathAtan is "atan".
	OperationMathAtan OperationMath = 5
	// OperationMathLog is "log".
	OperationMathLog OperationMath = 6
	// OperationMathLog10 is "log10".
	OperationMathLog10 OperationMath = 7
	// OperationMathExp is "exp".
	OperationMathExp OperationMath = 8
	// OperationMathExp10 is "exp10".
	OperationMathExp10 OperationMath = 9
	// OperationMathSinh is "sinh".
	OperationMathSinh OperationMath = 10
	// OperationMathCosh is "cosh".
	OperationMathCosh OperationMath = 11
	// OperationMathTanh is "tanh".
	OperationMathTanh OperationMath = 12
	// OperationMathAsinh is "asinh".
	OperationMathAsinh OperationMath = 13
	// OperationMathAcosh is "acosh".
	OperationMathAcosh OperationMath = 14
	// OperationMathAtanh is "atanh".
	OperationMathAtanh OperationMath = 15
)

// String returns the libvips nickname for this value.
func (v OperationMath) String() string {
	switch v {
	case 0:
		return "sin"
	case 1:
		return "cos"
	case 2:
		return "tan"
	case 3:
		return "asin"
	case 4:
		return "acos"
	case 5:
		return "atan"
	case 6:
		return "log"
	case 7:
		return "log10"
	case 8:
		return "exp"
	case 9:
		return "exp10"
	case 10:
		return "sinh"
	case 11:
		return "cosh"
	case 12:
		return "tanh"
	case 13:
		return "asinh"
	case 14:
		return "acosh"
	case 15:
		return "atanh"
	}
	return "OperationMath(" + itoa(int(v)) + ")"
}

// OperationMath2 mirrors the libvips VipsOperationMath2 type.
type OperationMath2 int

const (
	// OperationMath2Pow is "pow".
	OperationMath2Pow OperationMath2 = 0
	// OperationMath2Wop is "wop".
	OperationMath2Wop OperationMath2 = 1
	// OperationMath2Atan2 is "atan2".
	OperationMath2Atan2 OperationMath2 = 2
)

// String returns the libvips nickname for this value.
func (v OperationMath2) String() string {
	switch v {
	case 0:
		return "pow"
	case 1:
		return "wop"
	case 2:
		return "atan2"
	}
	return "OperationMath2(" + itoa(int(v)) + ")"
}

// OperationMorphology mirrors the libvips VipsOperationMorphology type.
type OperationMorphology int

const (
	// OperationMorphologyErode is "erode".
	OperationMorphologyErode OperationMorphology = 0
	// OperationMorphologyDilate is "dilate".
	OperationMorphologyDilate OperationMorphology = 1
)

// String returns the libvips nickname for this value.
func (v OperationMorphology) String() string {
	switch v {
	case 0:
		return "erode"
	case 1:
		return "dilate"
	}
	return "OperationMorphology(" + itoa(int(v)) + ")"
}

// OperationRelational mirrors the libvips VipsOperationRelational type.
type OperationRelational int

const (
	// OperationRelationalEqual is "equal".
	OperationRelationalEqual OperationRelational = 0
	// OperationRelationalNoteq is "noteq".
	OperationRelationalNoteq OperationRelational = 1
	// OperationRelationalLess is "less".
	OperationRelationalLess OperationRelational = 2
	// OperationRelationalLesseq is "lesseq".
	OperationRelationalLesseq OperationRelational = 3
	// OperationRelationalMore is "more".
	OperationRelationalMore OperationRelational = 4
	// OperationRelationalMoreeq is "moreeq".
	OperationRelationalMoreeq OperationRelational = 5
)

// String returns the libvips nickname for this value.
func (v OperationRelational) String() string {
	switch v {
	case 0:
		return "equal"
	case 1:
		return "noteq"
	case 2:
		return "less"
	case 3:
		return "lesseq"
	case 4:
		return "more"
	case 5:
		return "moreeq"
	}
	return "OperationRelational(" + itoa(int(v)) + ")"
}

// OperationRound mirrors the libvips VipsOperationRound type.
type OperationRound int

const (
	// OperationRoundRint is "rint".
	OperationRoundRint OperationRound = 0
	// OperationRoundCeil is "ceil".
	OperationRoundCeil OperationRound = 1
	// OperationRoundFloor is "floor".
	OperationRoundFloor OperationRound = 2
)

// String returns the libvips nickname for this value.
func (v OperationRound) String() string {
	switch v {
	case 0:
		return "rint"
	case 1:
		return "ceil"
	case 2:
		return "floor"
	}
	return "OperationRound(" + itoa(int(v)) + ")"
}

// PCS mirrors the libvips VipsPCS type.
type PCS int

const (
	// PCSLab is "lab".
	PCSLab PCS = 0
	// PCSXyz is "xyz".
	PCSXyz PCS = 1
)

// String returns the libvips nickname for this value.
func (v PCS) String() string {
	switch v {
	case 0:
		return "lab"
	case 1:
		return "xyz"
	}
	return "PCS(" + itoa(int(v)) + ")"
}

// Precision mirrors the libvips VipsPrecision type.
type Precision int

const (
	// PrecisionInteger is "integer".
	PrecisionInteger Precision = 0
	// PrecisionFloat is "float".
	PrecisionFloat Precision = 1
	// PrecisionApproximate is "approximate".
	PrecisionApproximate Precision = 2
)

// String returns the libvips nickname for this value.
func (v Precision) String() string {
	switch v {
	case 0:
		return "integer"
	case 1:
		return "float"
	case 2:
		return "approximate"
	}
	return "Precision(" + itoa(int(v)) + ")"
}

// RegionShrink mirrors the libvips VipsRegionShrink type.
type RegionShrink int

const (
	// RegionShrinkMean is "mean".
	RegionShrinkMean RegionShrink = 0
	// RegionShrinkMedian is "median".
	RegionShrinkMedian RegionShrink = 1
	// RegionShrinkMode is "mode".
	RegionShrinkMode RegionShrink = 2
	// RegionShrinkMax is "max".
	RegionShrinkMax RegionShrink = 3
	// RegionShrinkMin is "min".
	RegionShrinkMin RegionShrink = 4
	// RegionShrinkNearest is "nearest".
	RegionShrinkNearest RegionShrink = 5
)

// String returns the libvips nickname for this value.
func (v RegionShrink) String() string {
	switch v {
	case 0:
		return "mean"
	case 1:
		return "median"
	case 2:
		return "mode"
	case 3:
		return "max"
	case 4:
		return "min"
	case 5:
		return "nearest"
	}
	return "RegionShrink(" + itoa(int(v)) + ")"
}

// SdfShape mirrors the libvips VipsSdfShape type.
type SdfShape int

const (
	// SdfShapeCircle is "circle".
	SdfShapeCircle SdfShape = 0
	// SdfShapeBox is "box".
	SdfShapeBox SdfShape = 1
	// SdfShapeRoundedBox is "rounded-box".
	SdfShapeRoundedBox SdfShape = 2
	// SdfShapeLine is "line".
	SdfShapeLine SdfShape = 3
)

// String returns the libvips nickname for this value.
func (v SdfShape) String() string {
	switch v {
	case 0:
		return "circle"
	case 1:
		return "box"
	case 2:
		return "rounded-box"
	case 3:
		return "line"
	}
	return "SdfShape(" + itoa(int(v)) + ")"
}

// Size mirrors the libvips VipsSize type.
type Size int

const (
	// SizeBoth is "both".
	SizeBoth Size = 0
	// SizeUp is "up".
	SizeUp Size = 1
	// SizeDown is "down".
	SizeDown Size = 2
	// SizeForce is "force".
	SizeForce Size = 3
)

// String returns the libvips nickname for this value.
func (v Size) String() string {
	switch v {
	case 0:
		return "both"
	case 1:
		return "up"
	case 2:
		return "down"
	case 3:
		return "force"
	}
	return "Size(" + itoa(int(v)) + ")"
}

// TextWrap mirrors the libvips VipsTextWrap type.
type TextWrap int

const (
	// TextWrapWord is "word".
	TextWrapWord TextWrap = 0
	// TextWrapChar is "char".
	TextWrapChar TextWrap = 1
	// TextWrapWordChar is "word-char".
	TextWrapWordChar TextWrap = 2
	// TextWrapNone is "none".
	TextWrapNone TextWrap = 3
)

// String returns the libvips nickname for this value.
func (v TextWrap) String() string {
	switch v {
	case 0:
		return "word"
	case 1:
		return "char"
	case 2:
		return "word-char"
	case 3:
		return "none"
	}
	return "TextWrap(" + itoa(int(v)) + ")"
}

// itoa avoids pulling strconv into generated code for one call site.
func itoa(v int) string {
	if v == 0 {
		return "0"
	}
	neg := v < 0
	if neg {
		v = -v
	}
	var buf [20]byte
	i := len(buf)
	for v > 0 {
		i--
		buf[i] = byte('0' + v%10)
		v /= 10
	}
	if neg {
		i--
		buf[i] = '-'
	}
	return string(buf[i:])
}
